Repository cvmfs/cvmfs, pull requests merged in 2024-10, with the labels that each got.

#3662 Add support for supervisord in place of systemd
  cvmfs/server/cvmfs_server_apache.sh
  cvmfs/server/cvmfs_server_coda.sh
  cvmfs/server/cvmfs_server_util.sh
Labels: improvement, in:Server

#3513 Add support for high-precision timestamps
  cvmfs/CMakeLists.txt
  cvmfs/catalog_sql.cc
  cvmfs/catalog_sql.h
  cvmfs/directory_entry.cc
  cvmfs/directory_entry.h
  cvmfs/publish/settings.cc
  cvmfs/publish/settings.h
  cvmfs/server/cvmfs_server_ingest.sh
  cvmfs/server/cvmfs_server_publish.sh
  cvmfs/sql.h
  cvmfs/swissknife_ingest.cc
  cvmfs/swissknife_ingest.h
  cvmfs/swissknife_migrate.cc
  cvmfs/swissknife_sync.cc
  cvmfs/swissknife_sync.h
  cvmfs/sync_item.cc
  cvmfs/sync_item.h
  cvmfs/sync_item_dummy.cc
  cvmfs/sync_item_dummy.h
  cvmfs/sync_item_tar.cc
  cvmfs/sync_item_tar.h
  cvmfs/sync_mediator.cc
  test/src/500-mkrepo/main
  test/src/652-tarball_ingest_various_paths/main
  test/unittests/CMakeLists.txt
  test/unittests/t_catalog_sql.cc
Labels: new feature

#3679 Print correct timezone in logbuffer
  cvmfs/magic_xattr.cc
  cvmfs/util/string.cc
  cvmfs/util/string.h
  test/unittests/t_util.cc
Labels: in:Client
