Repository cvmfs/cvmfs, pull requests merged in 2025-04, with the labels that each got.

#3801 Avoid silent errors in externals build scripts
  bootstrap.sh
  externals/c-ares/src/configureHook.sh
  externals/c-ares/src/makeHook.sh
  externals/go/src/configureHook.sh
  externals/go/src/makeHook.sh
  externals/googlebench/src/makeHook.sh
  externals/googletest/src/configureHook.sh
  externals/googletest/src/makeHook.sh
  externals/leveldb/src/configureHook.sh
  externals/leveldb/src/makeHook.sh
  externals/libarchive/src/configureHook.sh
  externals/libarchive/src/makeHook.sh
  externals/libcrypto/src/configureHook.sh
  externals/libcrypto/src/makeHook.sh
  externals/libcurl/src/configureHook.sh
  externals/libcurl/src/makeHook.sh
  externals/maxminddb/src/configureHook.sh
  externals/maxminddb/src/makeHook.sh
  externals/pacparser/src/configureHook.sh
  externals/pacparser/src/makeHook.sh
  externals/protobuf/src/configureHook.sh
  externals/protobuf/src/makeHook.sh
  externals/rapidcheck/src/makeHook.sh
  externals/sha3/src/configureHook.sh
  externals/sha3/src/makeHook.sh
  externals/sparsehash/src/configureHook.sh
  externals/sparsehash/src/makeHook.sh
  externals/sqlite3/src/configureHook.sh
  externals/sqlite3/src/makeHook.sh
  externals/ssl/src/configureHook.sh
  externals/ssl/src/makeHook.sh
  externals/vjson/src/configureHook.sh
  externals/vjson/src/makeHook.sh
  externals/zlib/src/configureHook.sh
  externals/zlib/src/makeHook.sh
Labels: in:Build System

#3816 ci: fix sudo in build image
  test/common/container/Dockerfile-dev
Labels: in:Build System, in:Infrastructure

#3814 ducc: add log level cli and trace http get requests
  ci/run_unittests.sh
  ducc/cmd/root.go
  ducc/go.mod
  ducc/go.sum
  ducc/lib/image.go
  ducc/vendor/github.com/aoliveti/curling/.gitignore
  ducc/vendor/github.com/aoliveti/curling/LICENSE
  ducc/vendor/github.com/aoliveti/curling/README.md
  ducc/vendor/github.com/aoliveti/curling/command.go
  ducc/vendor/github.com/aoliveti/curling/option.go
  ducc/vendor/modules.txt
Labels: in:Container Tools
